name: report bug
description: Form to report bug
title: "[Bug-report]: "
label: ["bug', "approval"]
#assignees
body:
  - type: markdown
    attributes:
      value: |
        Please fill the following details to report a bug.
  
  - type: input
    id: customer-name
    attributes:
      label: Customer Name
      placeholder: "Enter Customer Name"
  
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: "Provide a brief summary"
  
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "Provide a brief description"
  
  - type: dropdown
    id: environment-type
    attributes:
      label: Environment Type
      options:
        - SAAS
        - ONPREM
        - BOTH
      default: 0
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P1
        - P2
        - P3
        - P4
      default: 0
  
  - type: textarea
    id: outcome-expected
    attributes:
      label: Outcome Expected
      placeholder: "Provide the expected outcome"
  
  - type: textarea
    id: uat-feedback
    attributes:
      label: UAT Feedback 
      placeholder: "Please provide user acceptance feedback"
  
  - type: input
    id: review-due-date
    attributes:
      label: Review Due Date 
      placeholder: "DD-MM-YYYY"
  
  - type: checkboxes
    id: working-as-desired
    attributes:
      label: Working As Desired 
      options:
        - label: "Yes"
        - label: "No"
  
  - type: textarea
    id: service-feedback
    attributes:
      label: Service Feedback 
      placeholder: "Please provide us your feedback"
