name: Request a POC
description: Request POC for a new customer.
title: "[0.POC]:"
labels: ["POC"]
# projects: ["bloo-team/30", "bloo-team/12"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this POC request! To address this as fast as possible, we need some information.
  - type: input
    id: customer-name
    attributes:
      label: Customer Name
      placeholder: "Enter Customer name"
   
  - type: input
    id: cluster-name
    attributes:
      label: Cluster Name
      placeholder: "Cluster name"
   
  - type: dropdown
    id: region
    attributes:
      label: Region
      options:
        - India
        - US
      default: 0
  
  - type: input
    id: license-volume
    attributes:
      label: License Volume
      placeholder: "100 GB/Day"
  
  - type: dropdown
    id: overage-allowed
    attributes:
      label: Overage Allowed
      options:
        - "Yes"
        - "No"
      default: 0
   
  - type: dropdown
    id: license-plan
    attributes:
      label: License Plan
      options:
        - Professional
        - Entereprise
        - Essential
      default: 0
   
  - type: textarea
    id: devices-list
    attributes:
      label: List of devices to integrate
      placeholder: "Windows servers, Sophos firewall, AD and Linux Servers."
  
  - type: input
    id: start-date
    attributes:
      label: Setup Start Date
      placeholder: "DD/MM/YYYY"
  
  - type: checkboxes
    id: log-source
    attributes:
      label: Customer Log Source (Multi Select)
      options:
        - label: PICO
        - label: DS
      
