name: Duplicate Issue and Reassign

# This workflow is triggered when an issue is closed.
on:
  issues:
    types: [closed]

jobs:
  duplicate_and_reassign:
    runs-on: ubuntu-latest

    steps:
    - name: Duplicate the issue and assign it to a new assignee
      uses: actions-ecosystem/action-create-issue@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ github.event.issue.title }} (Reassigned)  
        body: ${{ github.event.issue.body }}   
        labels: ${{ toJSON(github.event.issue.labels.*.name) }}   
        assignees: ArnavKusurkar  
