name: Duplicate and assign
on:
  issues:
    types: [opened, closed]
jobs:
  duplicate_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Duplicate Issue
        if: contains(github.event.issue.labels.*.name, 'POC')
        uses: actions-ecosystem/action-create-issue@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          labels: ${{ toJSON(github.event.issue.labels.*.name) }}
          assignees: ArnavKusurkar












