name: "Manager Review"
on:
  issues:
    types: [opened,labeled]

jobs:
  manager-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check Manager Action
        if: contains(github.event.issue.labels.*.name, 'complete') || contains(github.event.issue.labels.*.name, 'not-planned')
        run: |
          if [[ "${{ github.event.issue.labels.*.name }}" == *"complete"* ]]; then
            echo "continue=1" >> $GITHUB_ENV
          elif [[ "${{ github.event.issue.labels.*.name }}" == *"not-planned"* ]]; then
            echo "continue=0" >> $GITHUB_ENV
          fi

      - name: Close as Not Planned
        if: env.continue == '0'
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "This issue is closed as not planned."
          gh issue edit ${{ github.event.issue.number }} --state closed --label "not-planned"

      - name: Forward to Next Team if Complete
        if: env.continue == '1'
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "This issue is marked as complete."
          gh issue edit ${{ github.event.issue.number }} --label "complete"
          gh issue edit ${{ github.event.issue.number }} --assignee "next-team-username"
