name: Issue Approval Workflow

on: 
  issues:
    types: [opened, edited, closed]

jobs:
  assign_manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Assign Issue to Manager
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          gh issue edit $ISSUE_NUMBER --add-assignee Omkar-CyberBay --repo Omkar-CyberBay/desktop-tutorial
