name: "Manager Review Workflow"

on:
  issues:
    types: [labeled]

jobs:
  manager-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Manager's Label
        run: |
          if [[ "${{ github.event.label.name }}" == "complete" ]]; then
            echo "Issue marked as complete. Forwarding to the next team."
            echo "next_step=1" >> $GITHUB_ENV
          elif [[ "${{ github.event.label.name }}" == "not-planned" ]]; then
            echo "Issue marked as not planned. Closing the issue."
            echo "next_step=0" >> $GITHUB_ENV
          fi

      - name: Close Issue as Not Planned
        if: env.next_step == '0'
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "The product manager has marked this issue as 'not planned'. Closing it."
          gh issue edit ${{ github.event.issue.number }} --state closed

      - name: Forward Issue to Next Team if Complete
        if: env.next_step == '1'
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "The product manager has approved this issue. Forwarding it to the next team."
          gh issue edit ${{ github.event.issue.number }} --add-assignee "next-team-username"
