name: Issue Approval Workflow

on: 
  issues:
    types: [opened, edited, closed, labeled]

jobs:
  assign_manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh auth login --with-token <<< $GH_TOKEN
        
      - name: Assign Issue to Manager
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          gh issue edit $ISSUE_NUMBER --add-assignee Omkar-Net-Mon --repo Omkar-CyberBay/desktop-tutorial

      - name: Check Manager Label
        run: |
          if [[ "${{ github.event.label.name }}" == "complete" ]]; then
            echo "Issue marked as complete. Forwarding to the next team."
            echo "next_step=1" >> $GITHUB_ENV
          elif [[ "${{ github.event.label.name }}" == "not-planned" ]]; then
            echo "Issue marked as not planned. Closing the issue."
            echo "next_step=0" >> $GITHUB_ENV
          fi
      - name: Forward Issue to Next Team if Complete
        if: env.next_step == '1'
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "The product manager has approved this issue. Forwarding it to the next team."
          gh issue edit ${{ github.event.issue.number }} --add-assignee "ArnavKusurkar"
      - name: Close Issue as Not Planned
        if: env.next_step == '0'
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "The product manager has marked this issue as 'not planned'. Closing it."
          gh issue edit ${{ github.event.issue.number }} --state closed

          
      
          
