name: Issue Approval Workflow

on: [issues]

jobs:
  assign_maneger:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue to Manager
        run: |
          ISSUE_NUMBER=${{github.event.issue.number}}

          gh issue edit $ISSUE_NUMBER --add-assignee Omkar-CyberBay --repo Omkar-CyberBay/desktop-tutorial
        env:
          GH_TOKEN: ${{ github.token }}

          
      
