name: Duplicate and Assign Bug Report Issue
on:
  issues:
    types: [opened, closed]

jobs:
  duplicate_issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'POC')
    steps:
      - name: Duplicate the Bug Report Issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          labels: ${{ toJSON(github.event.issue.labels.*.name) }}
          assignees: ArnavKusurkar
        
       
