name: Issue Approval Workflow

on: [issues]

jobs:
  assign_maneger:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue to Manager
        run: |
          MANAGER_USERNAME='Omkar-Net-Mon'
          ISSUE_NUMBER=${{github.event.issue.number}}

          gh issue edit $ISSUE_NUMBER --assignee $MANAGER_USERNAME
          
      
