name: Duplicate Issue

on:
  issues:
    types: [opened]

jobs:
  duplicate_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Duplicate the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          ASSIGNEE: 'ArnavKusurkar'
        run: |
          TITLE=$(gh issue view $ISSUE_NUMBER --repo $REPO --json title -q '.title')
          BODY=$(gh issue view $ISSUE_NUMBER --repo $REPO --json body -q '.body')
          gh issue create --repo $REPO --title "$TITLE (New-Issue)" --body "$BODY" --assignee "$ASSIGNEE"
