name: Duplicate Issue

on:
  issues:
    types: [closed]

jobs:
  duplicate_issue:
    if: "contains(github.event.issue.title, '(Duplicate-Issue)')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Duplicate the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          ASSIGNEE: 'ArnavKusurkar' # Replace with actual username or team
        run: |
          title=$(gh issue view $ISSUE_NUMBER --repo $REPO --json title -q '.title')
          body=$(gh issue view $ISSUE_NUMBER --repo $REPO --json body -q '.body')
          gh issue create --repo $REPO --title "$TITLE (New-Issue)" --body "$BODY" --assignee "$ASSIGNEE"
