name: Final Issue

on:
  issues:
    types: [closed]

jobs:
  final_issue:
    if: startsWith(github.event.issue.title, '2.[POC]:')
    runs-on: ubuntu-latest

    steps:
       - name: Checkout the repository
         uses: actions/checkout@v2

       - name: Authenticate with GitHub CLI
         run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      
