name: Final Issue

on:
  issues:
    types: [closed]

jobs:
  final_issue:
    if: startsWith(github.event.issue.title, '2.[POC]:') && (github.event.issue.state_reason == 'completed')
    runs-on: ubuntu-latest

    steps:
       - name: Checkout the repository
         uses: actions/checkout@v2

       - name: Authenticate with GitHub CLI
         run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

       - name: One last Duplicate issue
         env:
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            REPO: ${{ github.repository }}
            ASSIGNEE1: 'Omkar-Net-Mon' 
         run: |
            # Retrieve the title of the issue
            TITLE=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json title -q '.title')
            
            # Retrieve the body of the issue
            BODY=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json body -q '.body')
            
            # Split the title after '-'
            IFS='-' read -ra titleArray <<< "$TITLE"
            TI1=${titleArray[0]}
            FINAL="$TI1-(CLOUD)"
            echo "Final: $FINAL"
            
            # Fetch the state reason
            STATE_REASON=$(gh issue list --search "$FINAL" --repo "$REPO" --json stateReason,title,state -s closed -q '.[0].stateReason')
            echo "State reason: $STATE_REASON"
            
            # Conditional actions based on STATE_REASON
            if [[ "$STATE_REASON" == "COMPLETED" ]]; then
              gh issue create --repo "$REPO" --title "$TI1 -(DARC)" --body "$BODY" --assignee "$ASSIGNEE1" --label "POC"
              echo "Both issues are 'completed'."
            elif [[ "$STATE_REASON" == "NOT_PLANNED" ]]; then
              echo "not_planned"
            else
              echo "State reason is neither 'completed' nor 'not_planned'. No action taken."
            fi
