name: Final Issue

on:
  issues:
    types: [closed]

jobs:
  final_issue:
    if: startsWith(github.event.issue.title, '2.[POC]:') && startsWith(github.event.issue.title, '3.[POC]:')
    runs-on: ubuntu-latest

    steps:
       - name: Checkout the repository
         uses: actions/checkout@v2

       - name: Authenticate with GitHub CLI
         run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"
       - name: One last Duplicate issue
         env:
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            REPO: ${{ github.repository }}
            ASSIGNEE1: 'Omkar-Net-Mon' 
         run: |
           ISSUE_CHECK1=$(gh issue list --repo "Omkar-CyberBay/desktop-tutorial" --search "$TITLE" --json title -q '.[0].title')
           IFS='-' && read -ra titleArray <<< "$ISSUE_CHECK1"
           ISSUE_CHECK12=${titleArray[1]}
           BODY=$(gh issue view $ISSUE_NUMBER --repo $REPO --json body -q '.body')
           ISSUE_CHECK1=$(gh issue view "$ISSUE_NUMBER" --repo "Omkar-CyberBay/desktop-tutorial" --json stateReason -q '.stateReason')
           echo "ISSUE_CHECK1: '$ISSUE_CHECK1'"
           ISSUE_CHECK2=$(gh issue view "$ISSUE_NUMBER" --repo "Omkar-CyberBay/desktop-tutorial" --json stateReason -q '.stateReason')
           echo "ISSUE_CHECK2: '$ISSUE_CHECK2'"
        

           if [[ "$ISSUE_CHECK1" == "COMPLETED" && "$ISSUE_CHECK2" == "COMPLETED" ]]; then
            gh issue create --repo $REPO --title "4.$TITLE (DARC)" --body "$BODY" --assignee "$ASSIGNEE1" --label "POC"
            echo "Both issues 2.[POC]and 2.[POC] are 'completed'."
           elif [[ "$ISSUE_CHECK1" == "COMPLETED" || "$ISSUE_CHECK2" == "NOT_PLANNED" ]]; then
            echo "No duplicate issue created as the statereason is 'not_planned'."
           elif [[ "$ISSUE_CHECK1" == "NOT_PLANNED" || "$ISSUE_CHECK2" == "COMPLETED" ]]; then
            echo "No duplicate issue created as the statereason is 'not_planned'."
           else
            echo "State reason is neither 'completed' nor 'not_planned'. No action taken."
           fi

     


           
           

         
           
      

      
