name: Duplicate Issue

on:
  issues:
    types: [opened]

jobs:
  duplicate_issue:
    if: github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'POC')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Duplicate the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          ASSIGNEE: 'Omkar-Net-Mon'
        run: |
          TITLE=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json title -q '.title')
          BODY=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json body -q '.body')
          DUPLICATE_CHECK=$(gh issue list --repo "$REPO" --search "${TITLE}" --json number -q '.[] | .number')

          if [ -z "$DUPLICATE_CHECK" ]; then
            gh issue create --repo "$REPO" --title "0. $TITLE APPROVAL" --body "$BODY" --assignee "$ASSIGNEE"
            echo "Duplicate issue created."
          else
            echo "Duplicate issue already exists. No action taken."
          fi
