name: Split Issue

on:
  issues:
    types: [closed]

jobs:
  duplicate_issue:
    if: contains(github.event.issue.labels.*.name, 'approval') && startsWith(github.event.issue.title, '1.0.[POC]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Duplicate the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          ASSIGNEE1: 'Omkar-Net-Mon' 
          ASSIGNEE2: 'Omkar-CyberBay'
        run: |
          TITLE=$(gh issue view $ISSUE_NUMBER --repo $REPO --json title -q '.title')
          BODY=$(gh issue view $ISSUE_NUMBER --repo $REPO --json body -q '.body')
          # DUPLICATE_CHECK=$(gh issue list --repo $REPO --search "0. ${TITLE}" --json number -q '.[] | .number')

          if [[ "${{ github.event.issue.state_reason }}" == "completed" ]]; then
            gh issue create --repo $REPO --title "3.$TITLE (LISENCE)" --body "$BODY" --assignee "$ASSIGNEE1" --label "lisence"
            gh issue create --repo $REPO --title "4.$TITLE (CLOUD)" --body "$BODY" --assignee "$ASSIGNEE2" --label "cloud"
            echo "Duplicate issues created."
          elif [[ "${{ github.event.issue.state_reason }}" == "not_planned" ]]; then
            echo "No duplicate issue created as the state reason is 'not_planned'."
          else
            echo "State reason is neither 'completed' nor 'not_planned'. No action taken."
          fi

        
         
          
